const PDFDocument = require('pdfkit');
const Transaction = require('../models/Transaction');
const User = require('../models/User');

// GET /api/reports/pdf
const generatePDFReport = async (req, res, next) => {
  try {
    const userId = req.user.id;
    const user = await User.findById(userId);
    const transactions = await Transaction.find({ userId }).sort({ date: -1 });

    // Calculate summary
    const totalIncome = transactions.filter((t) => t.type === 'income').reduce((s, t) => s + t.amount, 0);
    const totalExpense = transactions.filter((t) => t.type === 'expense').reduce((s, t) => s + t.amount, 0);
    const savings = totalIncome - totalExpense;

    // Category breakdown
    const categories = {};
    transactions.filter((t) => t.type === 'expense').forEach((t) => {
      categories[t.category] = (categories[t.category] || 0) + t.amount;
    });

    // Create PDF
    const doc = new PDFDocument({ margin: 50 });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=ExpenseIQ_Report_${Date.now()}.pdf`);
    doc.pipe(res);

    // Title
    doc.fontSize(24).fillColor('#4f46e5').text('ExpenseIQ', { align: 'center' });
    doc.fontSize(12).fillColor('#64748b').text('Smart Expense Tracker Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(10).fillColor('#94a3b8').text(`Generated on ${new Date().toLocaleDateString('en-IN')} for ${user.name}`, { align: 'center' });
    doc.moveDown(2);

    // Summary Section
    doc.fontSize(16).fillColor('#1e293b').text('Financial Summary');
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor('#334155');
    doc.text(`Total Income:    ₹${totalIncome.toLocaleString('en-IN')}`);
    doc.text(`Total Expense:   ₹${totalExpense.toLocaleString('en-IN')}`);
    doc.text(`Net Savings:     ₹${savings.toLocaleString('en-IN')}`);
    doc.text(`Transactions:    ${transactions.length}`);
    doc.moveDown(1.5);

    // Category Breakdown
    if (Object.keys(categories).length > 0) {
      doc.fontSize(16).fillColor('#1e293b').text('Expense by Category');
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor('#334155');
      const sortedCats = Object.entries(categories).sort((a, b) => b[1] - a[1]);
      sortedCats.forEach(([cat, amount]) => {
        const pct = totalExpense > 0 ? ((amount / totalExpense) * 100).toFixed(1) : 0;
        doc.text(`  ${cat}: ₹${amount.toLocaleString('en-IN')} (${pct}%)`);
      });
      doc.moveDown(1.5);
    }

    // Recent Transactions
    doc.fontSize(16).fillColor('#1e293b').text('Recent Transactions');
    doc.moveDown(0.5);

    // Table header
    const tableTop = doc.y;
    doc.fontSize(9).fillColor('#64748b');
    doc.text('Date', 50, tableTop, { width: 80 });
    doc.text('Type', 130, tableTop, { width: 60 });
    doc.text('Category', 190, tableTop, { width: 90 });
    doc.text('Amount', 280, tableTop, { width: 80, align: 'right' });
    doc.text('Note', 370, tableTop, { width: 180 });
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke('#e2e8f0');
    doc.moveDown(0.3);

    // Table rows (max 30)
    const displayTx = transactions.slice(0, 30);
    doc.fontSize(9).fillColor('#334155');
    displayTx.forEach((tx) => {
      const y = doc.y;
      if (y > 700) {
        doc.addPage();
      }
      const dateStr = tx.date ? new Date(tx.date).toLocaleDateString('en-IN') : '-';
      doc.text(dateStr, 50, doc.y, { width: 80 });
      doc.text(tx.type, 130, doc.y - 12, { width: 60 });
      doc.text(tx.category, 190, doc.y - 12, { width: 90 });
      doc.fillColor(tx.type === 'income' ? '#10b981' : '#ef4444');
      doc.text(`₹${tx.amount.toLocaleString('en-IN')}`, 280, doc.y - 12, { width: 80, align: 'right' });
      doc.fillColor('#334155');
      doc.text(tx.note || '-', 370, doc.y - 12, { width: 180 });
      doc.moveDown(0.3);
    });

    // Footer
    doc.moveDown(2);
    doc.fontSize(8).fillColor('#94a3b8').text('This report was auto-generated by ExpenseIQ.', { align: 'center' });

    doc.end();
  } catch (error) {
    next(error);
  }
};

module.exports = { generatePDFReport };
